In [31]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px

In [32]:
df = pd.read_csv(r'C:\Users\jbasn\OneDrive\Documents\Raw data for loan approval ml model\loan_approval_data (1).csv')
df.head()

,id,age,income,home_ownership,emplyment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_allowed_loan
0,35437,21.0,12000,OWN,0,EDUCATION,15000,6.99,0.12,N,4,0,-2426900
1,53756,21.0,13200,OWN,2,EDUCATION,25000,16.77,0.19,Y,3,0,-111739
2,42205,23.0,9600,RENT,5,MEDICAL,30000,12.42,0.31,N,3,0,-89000
3,19180,40.0,182004,RENT,3,EDUCATION,35000,8.00,0.19,N,11,0,35000
4,28072,40.0,90000,MORTGAGE,3,HOMEIMPROVEMENT,35000,12.42,0.39,N,14,0,35000

In [33]:
df.shape

(58645, 13)

In [34]:
print("column names and dtypes")
df.dtypes

column names and dtypes

id                           int64
age                        float64
income                       int64
home_ownership              object
emplyment_length             int64
loan_intent                 object
loan_amount                  int64
loan_interest_rate         float64
loan_income_ratio          float64
payment_default_on_file     object
credit_history_length        int64
loan_approval_status         int64
max_allowed_loan             int64
dtype: object

In [35]:
df.describe()

,id,age,income,emplyment_length,loan_amount,loan_interest_rate,loan_income_ratio,credit_history_length,loan_approval_status,max_allowed_loan
count,58645.000000,58639.000000,5.864500e+04,58645.000000,58645.000000,58634.000000,58645.000000,58645.000000,58645.000000,5.864500e+04
mean,29322.000000,27.550913,6.404617e+04,4.703487,9217.556518,10.677526,0.159238,5.813556,0.142382,6.975472e+04
std,16929.497605,6.033217,3.793111e+04,4.004982,5563.807384,3.036034,0.091692,4.029196,0.349445,6.175091e+04
min,0.000000,20.000000,4.200000e+03,0.000000,500.000000,-11.140000,0.000000,2.000000,0.000000,-2.426900e+06
25%,14661.000000,23.000000,4.200000e+04,2.000000,5000.000000,7.880000,0.090000,3.000000,0.000000,3.800300e+04
50%,29322.000000,26.000000,5.800000e+04,4.000000,8000.000000,10.750000,0.140000,4.000000,0.000000,6.239200e+04
75%,43983.000000,30.000000,7.560000e+04,7.000000,12000.000000,12.990000,0.210000,8.000000,0.000000,9.271600e+04
max,58644.000000,123.000000,1.900000e+06,150.000000,35000.000000,23.220000,0.830000,30.000000,1.000000,2.638778e+06

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       58645 non-null  int64
 1   age                      58639 non-null  float64
 2   income                   58645 non-null  int64
 3   home_ownership           58645 non-null  object
 4   emplyment_length         58645 non-null  int64
 5   loan_intent              58645 non-null  object
 6   loan_amount              58645 non-null  int64
 7   loan_interest_rate       58634 non-null  float64
 8   loan_income_ratio        58645 non-null  float64
 9   payment_default_on_file  58640 non-null  object
 10  credit_history_length    58645 non-null  int64
 11  loan_approval_status     58645 non-null  int64
 12  max_allowed_loan         58645 non-null  int64
dtypes: float64(3), int64(7), object(3)
memory usage: 5.8+ MB

In [37]:
df.isnull().sum()

id                          0
age                         6
income                      0
home_ownership              0
emplyment_length            0
loan_intent                 0
loan_amount                 0
loan_interest_rate         11
loan_income_ratio           0
payment_default_on_file     5
credit_history_length       0
loan_approval_status        0
max_allowed_loan            0
dtype: int64

In [38]:
print("missing values as a percentage")
round(df.isnull().sum() / len(df) * 100, 2)

missing values as a percentage

id                         0.00
age                        0.01
income                     0.00
home_ownership             0.00
emplyment_length           0.00
loan_intent                0.00
loan_amount                0.00
loan_interest_rate         0.02
loan_income_ratio          0.00
payment_default_on_file    0.01
credit_history_length      0.00
loan_approval_status       0.00
max_allowed_loan           0.00
dtype: float64

In [39]:
print("checking for fully duplicated rows")
df.duplicated().sum()

checking for fully duplicated rows

np.int64(0)

In [40]:
print("droping duplicated files")
df.drop_duplicates(inplace=True)

droping duplicated files

In [41]:
df.drop('id',axis= 1,inplace=True)

In [42]:
print("printing all columns as a  list")
list(df.columns)

printing all columns as a  list

['age',
 'income',
 'home_ownership',
 'emplyment_length',
 'loan_intent',
 'loan_amount',
 'loan_interest_rate',
 'loan_income_ratio',
 'payment_default_on_file',
 'credit_history_length',
 'loan_approval_status',
 'max_allowed_loan']

In [43]:
print("categorical columns")
df.select_dtypes(include=['object']).columns

categorical columns

Index(['home_ownership', 'loan_intent', 'payment_default_on_file'], dtype='object')

In [44]:
import plotly.express as px

missing = df.isnull().sum().reset_index()
missing.columns = ['column','Missing values']

fig = px.bar(
    missing,
    x='column',
    y='Missing values',
    title='Missing values for each column'
)

fig.show()

In [45]:
print("filling missing values of age")

df['age'] = df['age'].apply(lambda x : np.nan if x > 100 else x)
df['age'].fillna(df['age'].median(),inplace = True)

filling missing values of age

C:\Users\jbasn\AppData\Local\Temp\ipykernel_4968\763988236.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(),inplace = True)

In [46]:
df['loan_interest_rate'].fillna(df['loan_interest_rate'].median(), inplace=True)
mode_val = df['payment_default_on_file'].mode()[0]
df['payment_default_on_file'].fillna(mode_val, inplace=True)

C:\Users\jbasn\AppData\Local\Temp\ipykernel_4968\1537102106.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['loan_interest_rate'].fillna(df['loan_interest_rate'].median(), inplace=True)
C:\Users\jbasn\AppData\Local\Temp\ipykernel_4968\1537102106.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['payment_default_on_file'].fillna(mode_val, inplace=True)

In [47]:
df.isnull().sum()

age                        0
income                     0
home_ownership             0
emplyment_length           0
loan_intent                0
loan_amount                0
loan_interest_rate         0
loan_income_ratio          0
payment_default_on_file    0
credit_history_length      0
loan_approval_status       0
max_allowed_loan           0
dtype: int64